import Head from "next/head";
import Header from "../src/components/Header/index";
import Main from "../src/components/Main/index";
import Footer from "../src/components/Footer/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Loopstudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="container-80">
        <Main />
      </div>

      <Footer />
    </>
  );
}
